# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project'
require 'bubble-wrap/core'
require 'bubble-wrap/ui'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'BubbleWrap'
  app.codesign_certificate = 'iPhone Developer: Kim Dalsgaard (33BNQQR85G)'
end
